name: your-workflow-name
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    # optionally use a convenient Ubuntu LTS + DVC + CML image
    container: docker://dvcorg/cml-py3:latest
    steps:

      - name: Add missing GPG keys
        run: |
          curl -fsSL https://s3-us-east-2.amazonaws.com/dvc-s3-repo/deb/public.gpg | sudo gpg --dearmor -o /usr/share/keyrings/dvc-archive-keyring.gpg
          echo "deb [signed-by=/usr/share/keyrings/dvc-archive-keyring.gpg] https://s3-us-east-2.amazonaws.com/dvc-s3-repo/deb stable main" | sudo tee /etc/apt/sources.list.d/dvc.list
      - name: Install GLIBC
        run: |
          sudo apt update
          sudo apt install -y libc6
                
      - uses: iterative/setup-cml@v1
      - name: Train model
        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          python train.py
      - name: Write CML report
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Post reports as comments in GitHub PRs
          cat results.txt >> report.md
          cml comment create report.md
